Fix distro build order, remove debugging code, and fix indentation

diff --git a/scripts/build-probe-binaries b/scripts/build-probe-binaries
--- a/scripts/build-probe-binaries
+++ b/scripts/build-probe-binaries
@@ -467,6 +467,103 @@ function debian_build {
 
 if [ -z $KERNEL_TYPE ]; then
 	#
+	# Ubuntu build
+	#
+
+	echo Building Ubuntu
+	DIR=$(dirname $(readlink -f $0))
+	URLS="$($DIR/kernel-crawler.py Ubuntu)"
+
+	for URL in $URLS
+	do
+		ubuntu_build $URL
+	done
+
+	#
+	# RHEL build
+	#
+
+	echo Building RHEL
+	DIR=$(dirname $(readlink -f $0))
+	URLS="$($DIR/kernel-crawler.py CentOS)"
+
+	for URL in $URLS
+	do
+		rhel_build $URL
+	done
+
+	#
+	# Fedora build
+	#
+
+	echo Building Fedora
+	DIR=$(dirname $(readlink -f $0))
+	URLS="$($DIR/kernel-crawler.py Fedora)"
+
+	for URL in $URLS
+	do
+		rhel_build $URL
+	done
+
+	#
+	# CoreOS build
+	#
+	echo Building CoreOS
+	DIR=$(dirname $(readlink -f $0))
+	URLS="$($DIR/kernel-crawler.py CoreOS)"
+
+	for URL in $URLS
+	do
+		set +e
+		eval $(curl -s ${URL}version.txt)
+		if [ ${?} -ne 0 ]; then
+			echo "### Error fetching ${URL}version.txt ###"
+			continue
+		fi
+		set -e
+		if [ $COREOS_BUILD -gt 890 ]; then
+			coreos_build_new $URL $COREOS_VERSION
+		else
+			coreos_build_old $URL $COREOS_VERSION
+		fi
+	done
+
+	#
+	# boot2docker build
+	#
+	echo Building boot2docker
+	DIR=$(dirname $(readlink -f $0))
+	$DIR/boot2docker-kernel-crawler.py | \
+		while read KERNEL_ARGS
+		do
+			boot2docker_build $KERNEL_ARGS
+		done
+
+	#
+	# Debian build
+	#
+	echo Building Debian
+	DIR=$(dirname $(readlink -f $0))
+	URLS="$($DIR/kernel-crawler.py Debian)"
+
+	for URL in $URLS
+	do
+		debian_build $URL
+	done
+
+	#
+	# Oracle RHCK build
+	#
+	echo Building Oracle RHCK
+	DIR=$(dirname $(readlink -f $0))
+	URLS="$($DIR/oracle-kernel-crawler.py Oracle-RHCK)"
+
+	for URL in $URLS
+	do
+		rhel_build $URL
+	done
+
+	#
 	# The UEK builds needs to happen in a UEK environment, so we launch
 	# a container running OL and do the builds there. This container
 	# doesn't have git credentials, so it relies on previous builds
@@ -487,112 +584,12 @@ if [ -z $KERNEL_TYPE ]; then
 	docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi
 	docker run -it --rm --name ol7-build -v $BASEDIR:/build/probe ol7-builder $PROBE_NAME $PROBE_VERSION $REPOSITORY_NAME OL7-UEK
 
-	# XXX debugging, oracle uek needs to go after the other distros eventually
-	exit
+	#
+	# Upload modules
+	#
+	aws s3 sync ./output/ s3://download.draios.com/$REPOSITORY_NAME/sysdig-probe-binaries/ --acl public-read
 
-#
-# Ubuntu build
-#
-
-echo Building Ubuntu
-DIR=$(dirname $(readlink -f $0))
-URLS="$($DIR/kernel-crawler.py Ubuntu)"
-
-for URL in $URLS
-do
-	ubuntu_build $URL
-done
-
-#
-# RHEL build
-#
-
-echo Building RHEL
-DIR=$(dirname $(readlink -f $0))
-URLS="$($DIR/kernel-crawler.py CentOS)"
-
-for URL in $URLS
-do
-	rhel_build $URL
-done
-
-#
-# Fedora build
-#
-
-echo Building Fedora
-DIR=$(dirname $(readlink -f $0))
-URLS="$($DIR/kernel-crawler.py Fedora)"
-
-for URL in $URLS
-do
-	rhel_build $URL
-done
-
-#
-# CoreOS build
-#
-echo Building CoreOS
-DIR=$(dirname $(readlink -f $0))
-URLS="$($DIR/kernel-crawler.py CoreOS)"
-
-for URL in $URLS
-do
-	set +e
-		eval $(curl -s ${URL}version.txt)
-		if [ ${?} -ne 0 ]; then
-			echo "### Error fetching ${URL}version.txt ###"
-			continue
-		fi
-	set -e
-	if [ $COREOS_BUILD -gt 890 ]; then
-		coreos_build_new $URL $COREOS_VERSION
-	else
-		coreos_build_old $URL $COREOS_VERSION
-	fi
-done
-
-#
-# boot2docker build
-#
-echo Building boot2docker
-DIR=$(dirname $(readlink -f $0))
-$DIR/boot2docker-kernel-crawler.py | \
-while read KERNEL_ARGS
-do
-	boot2docker_build $KERNEL_ARGS
-done
-
-#
-# Debian build
-#
-echo Building Debian
-DIR=$(dirname $(readlink -f $0))
-URLS="$($DIR/kernel-crawler.py Debian)"
-
-for URL in $URLS
-do
-	debian_build $URL
-done
-
-#
-# Oracle RHCK build
-#
-echo Building Oracle RHCK
-DIR=$(dirname $(readlink -f $0))
-URLS="$($DIR/oracle-kernel-crawler.py Oracle-RHCK)"
-
-	for URL in $URLS
-	do
-		rhel_build $URL
-	done
-
-#
-# Upload modules
-#
-#aws s3 sync ./output/ s3://download.draios.com/$REPOSITORY_NAME/sysdig-probe-binaries/ --acl public-read
-
-echo "Success."
+	echo "Success."
 
 elif [ "OL6-UEK" = $KERNEL_TYPE ]; then
 	# This should only run in the ol6-builder container context
