log failures

diff --git a/scripts/build-probe-binaries b/scripts/build-probe-binaries
--- a/scripts/build-probe-binaries
+++ b/scripts/build-probe-binaries
@@ -20,6 +20,7 @@ BASEDIR=$(pwd)
 ARCH=$(uname -m)
 URL_TIMEOUT=300
 RETRY=10
+ERROR_LOG=()
 
 if [ $# -eq 4 ]; then
 	KERNEL_TYPE=$4
@@ -87,15 +88,22 @@ function build_probe {
 		cd build
 		version_name=-D$(echo $PROBE_REPO_NAME | tr [a-z] [A-Z])_VERSION
 
-		cmake -DCMAKE_BUILD_TYPE=Release $version_name=$PROBE_VERSION ..
-		make driver
+		set +e
+		cmake -DCMAKE_BUILD_TYPE=Release $version_name=$PROBE_VERSION .. && make driver
+		if [ ${?} -ne 0 ]; then
+			ERROR_LOG+=("$PROBE_NAME-$PROBE_VERSION-$ARCH-$KERNEL_RELEASE-$HASH.ko")
+			return
+		fi
+
 		strip -g driver/$PROBE_NAME.ko
 
 		KO_VERSION=$(/sbin/modinfo driver/$PROBE_NAME.ko | grep vermagic | tr -s " " | cut -d " " -f 2)
 		if [ "$KO_VERSION" != "$KERNEL_RELEASE" ]; then
 			echo "Corrupted probe, KO_VERSION " $KO_VERSION ", KERNEL_RELEASE " $KERNEL_RELEASE
-			exit 1
+			ERROR_LOG+=("Corrupted probe, KO_VERSION $KO_VERSION $PROBE_NAME-$PROBE_VERSION-$ARCH-$KERNEL_RELEASE-$HASH.ko")
+			return
 		fi
+		set -e
 
 		cp driver/$PROBE_NAME.ko $BASEDIR/output/$PROBE_NAME-$PROBE_VERSION-$ARCH-$KERNEL_RELEASE-$HASH.ko
 		cp driver/$PROBE_NAME.ko $BASEDIR/output/$PROBE_NAME-$PROBE_VERSION-$ARCH-$KERNEL_RELEASE-$HASH_ORIG.ko
@@ -443,6 +451,19 @@ function debian_build {
 	cd ${BASEDIR}
 }
 
+function error_logging() {
+	if [ "${#ERROR_LOG[@]}" -gt 0 ]; then
+		echo "Failures:"
+		for item in "${ERROR_LOG[@]}"; do
+			echo "${item}"
+		done
+		exit 1
+	else
+		echo "Success."
+		exit 0
+	fi
+}
+
 if [ -z "$KERNEL_TYPE" ]; then
 	#
 	# Ubuntu build
@@ -576,8 +597,7 @@ if [ -z "$KERNEL_TYPE" ]; then
 	# Upload modules
 	#
 	aws s3 sync ./output/ s3://download.draios.com/$REPOSITORY_NAME/sysdig-probe-binaries/ --acl public-read
-
-	echo "Success."
+	error_logging
 
 elif [ "OL6-UEK" = "$KERNEL_TYPE" ]; then
 	# This should only run in the ol6-builder container context
@@ -589,6 +609,7 @@ elif [ "OL6-UEK" = "$KERNEL_TYPE" ]; then
 	do
 		rhel_build $URL
 	done
+	error_logging
 elif [ "OL7-UEK" = "$KERNEL_TYPE" ]; then
 	# This should only run in the ol7-builder container context
 	echo Building Oracle Linux 7 UEK
@@ -599,6 +620,7 @@ elif [ "OL7-UEK" = "$KERNEL_TYPE" ]; then
 	do
 		rhel_build $URL
 	done
+	error_logging
 else
 	exit 1
 fi
