Make output less noisy

diff --git a/scripts/build-probe-binaries b/scripts/build-probe-binaries
--- a/scripts/build-probe-binaries
+++ b/scripts/build-probe-binaries
@@ -92,8 +92,16 @@ function clean_sysdig {
 }
 
 function build_probe {
+	local rebuild_gcc_plugins="${1:-"false"}"
 
-	if [ ! -f $BASEDIR/output/$PROBE_NAME-$PROBE_VERSION-$ARCH-$KERNEL_RELEASE-$HASH.ko ] || [ ! -f $BASEDIR/output/$PROBE_NAME-$PROBE_VERSION-$ARCH-$KERNEL_RELEASE-$HASH_ORIG.ko ]; then
+	if [ ! -f $BASEDIR/output/$PROBE_NAME-$PROBE_VERSION-$ARCH-$KERNEL_RELEASE-$HASH.ko ] || \
+	   [ ! -f $BASEDIR/output/$PROBE_NAME-$PROBE_VERSION-$ARCH-$KERNEL_RELEASE-$HASH_ORIG.ko ]; then
+		# Rebuild the gcc-plugins if requested
+		if [[ "${rebuild_gcc_plugins}" == "true" ]]; then
+			# Don't generate noise if there's no such target
+			# Keep going if this fails
+			(cd "${KERNELDIR}" && make gcc-plugins 2&>1 | grep -v "No rule to make target") || true
+		fi
 
 	        echo Building $PROBE_NAME-$PROBE_VERSION-$ARCH-$KERNEL_RELEASE-$HASH.ko [${FUNCNAME[1]}]
 
@@ -339,11 +347,14 @@ function ubuntu_build {
 function rhel_build {
 
 	#
-	# The function just requires the rpm url
+	# ${1} - the URL to fetch
+	# ${2} - should gcc plugins be rebuilt (default: false)
 	#
 
 	# Get all the parameters needed
 	URL=$1
+	local rebuild_gcc_plugins="${2:-"false"}"
+
 	RPM=$(echo $URL | grep -o '[^/]*$')
 	KERNEL_RELEASE=$(echo $RPM | awk 'match($0, /[^kernel\-(uek\-)?(core\-|devel\-)?].*[^(\.rpm)]/){ print substr($0, RSTART, RLENGTH) }')
 
@@ -374,11 +385,10 @@ function rhel_build {
 		HASH_ORIG=$HASH
 
 		export KERNELDIR=$BASEDIR/$KERNEL_RELEASE/usr/src/kernels/$KERNEL_RELEASE
-		cd "${KERNELDIR}" && make gcc-plugins || true
 
 		cd $BASEDIR
 
-		build_probe
+		build_probe "${rebuild_gcc_plugins}"
 	fi
 
 	cd $BASEDIR
@@ -561,7 +571,7 @@ if [ -z "$KERNEL_TYPE" ]; then
 
 	for URL in $URLS
 	do
-		rhel_build $URL
+		rhel_build $URL "true"
 	done
 
 	#
