log failures

diff --git a/scripts/build-probe-binaries b/scripts/build-probe-binaries
--- a/scripts/build-probe-binaries
+++ b/scripts/build-probe-binaries
@@ -35,6 +35,10 @@ else
 	PROBE_REPO_NAME=$(echo $PROBE_NAME | cut -f1 -d-)
 fi
 
+if [ -z ${ERROR_LOG+x} ]; then
+	ERROR_LOG=/dev/null
+fi
+
 function update_code_for {
 	repo=$1
 	if [ ! -d $repo ]; then
@@ -454,7 +458,7 @@ if [ -z "$KERNEL_TYPE" ]; then
 
 	for URL in $URLS
 	do
-		ubuntu_build $URL
+		ubuntu_build $URL || echo "$URL" | tee -a ${ERROR_LOG}
 	done
 
 	#
@@ -467,7 +471,7 @@ if [ -z "$KERNEL_TYPE" ]; then
 
 	for URL in $URLS
 	do
-		rhel_build $URL
+		rhel_build $URL || echo "$URL" | tee -a ${ERROR_LOG}
 	done
 
 	#
@@ -480,7 +484,7 @@ if [ -z "$KERNEL_TYPE" ]; then
 
 	for URL in $URLS
 	do
-		rhel_build $URL
+		rhel_build $URL || echo "$URL" | tee -a ${ERROR_LOG}
 	done
 
 	#
@@ -500,9 +504,9 @@ if [ -z "$KERNEL_TYPE" ]; then
 		fi
 		set -e
 		if [ $COREOS_BUILD -gt 890 ]; then
-			coreos_build_new $URL $COREOS_VERSION
+			coreos_build_new $URL $COREOS_VERSION || echo "$URL $COREOS_VERSION" | tee -a ${ERROR_LOG}
 		else
-			coreos_build_old $URL $COREOS_VERSION
+			coreos_build_old $URL $COREOS_VERSION || echo "$URL $COREOS_VERSION" | tee -a ${ERROR_LOG}
 		fi
 	done
 
@@ -526,7 +530,7 @@ if [ -z "$KERNEL_TYPE" ]; then
 
 	for URL in $URLS
 	do
-		debian_build $URL
+		debian_build $URL || echo "$URL" | tee -a ${ERROR_LOG}
 	done
 	# XXX agent/434 - We need to force a build for certain kernel versions
 	# because they are still in use by some GCE customers but the headers
@@ -544,7 +548,7 @@ if [ -z "$KERNEL_TYPE" ]; then
 
 	for URL in $URLS
 	do
-		rhel_build $URL
+		rhel_build $URL || echo "$URL" | tee -a ${ERROR_LOG}
 	done
 
 	#
@@ -581,7 +585,7 @@ if [ -z "$KERNEL_TYPE" ]; then
 
 	for URL in $URLS
 	do
-		rhel_build $URL
+		rhel_build $URL || echo "$URL" | tee -a ${ERROR_LOG}
 	done
 
 	#
@@ -590,7 +594,6 @@ if [ -z "$KERNEL_TYPE" ]; then
 	#if [ $PROBE_NAME = "falco-probe" ]; then
 	#	aws s3 sync ./output/ s3://download.draios.com/$REPOSITORY_NAME/sysdig-probe-binaries/ --acl public-read
 	#fi
-
 	echo "Success."
 
 elif [ "OL6-UEK" = "$KERNEL_TYPE" ]; then
@@ -601,7 +604,7 @@ elif [ "OL6-UEK" = "$KERNEL_TYPE" ]; then
 
 	for URL in $URLS
 	do
-		rhel_build $URL
+		rhel_build $URL || echo "$URL" | tee -a ${ERROR_LOG}
 	done
 elif [ "OL7-UEK" = "$KERNEL_TYPE" ]; then
 	# This should only run in the ol7-builder container context
@@ -611,7 +614,7 @@ elif [ "OL7-UEK" = "$KERNEL_TYPE" ]; then
 
 	for URL in $URLS
 	do
-		rhel_build $URL
+		rhel_build $URL || echo "$URL" | tee -a ${ERROR_LOG}
 	done
 else
 	exit 1
