log failures to file, check file size at end to determine exit code

diff --git a/scripts/build-probe-binaries b/scripts/build-probe-binaries
--- a/scripts/build-probe-binaries
+++ b/scripts/build-probe-binaries
@@ -20,7 +20,7 @@ BASEDIR=$(pwd)
 ARCH=$(uname -m)
 URL_TIMEOUT=300
 RETRY=10
-ERROR_LOG=()
+ERROR_FILE="${BASEDIR}/probe_build_failures"
 
 if [ $# -eq 4 ]; then
 	KERNEL_TYPE=$4
@@ -34,6 +34,10 @@ if [ $PROBE_NAME = "sysdigcloud-probe" ]; then
 	PROBE_REPO_NAME="agent"
 else
 	PROBE_REPO_NAME=$(echo $PROBE_NAME | cut -f1 -d-)
+fi
+
+if [ ! -f ${ERROR_FILE} ]; then
+	touch ${ERROR_FILE}
 fi
 
 function update_code_for {
@@ -91,7 +95,8 @@ function build_probe {
 		set +e
 		cmake -DCMAKE_BUILD_TYPE=Release $version_name=$PROBE_VERSION .. && make driver
 		if [ ${?} -ne 0 ]; then
-			ERROR_LOG+=("$PROBE_NAME-$PROBE_VERSION-$ARCH-$KERNEL_RELEASE-$HASH.ko")
+			echo "$PROBE_NAME-$PROBE_VERSION-$ARCH-$KERNEL_RELEASE-$HASH.ko" >> "${ERROR_FILE}"
+			cd ${BASEDIR}
 			return
 		fi
 
@@ -100,7 +105,8 @@ function build_probe {
 		KO_VERSION=$(/sbin/modinfo driver/$PROBE_NAME.ko | grep vermagic | tr -s " " | cut -d " " -f 2)
 		if [ "$KO_VERSION" != "$KERNEL_RELEASE" ]; then
 			echo "Corrupted probe, KO_VERSION " $KO_VERSION ", KERNEL_RELEASE " $KERNEL_RELEASE
-			ERROR_LOG+=("Corrupted probe, KO_VERSION $KO_VERSION $PROBE_NAME-$PROBE_VERSION-$ARCH-$KERNEL_RELEASE-$HASH.ko")
+			echo "Corrupted probe, KO_VERSION $KO_VERSION $PROBE_NAME-$PROBE_VERSION-$ARCH-$KERNEL_RELEASE-$HASH.ko" >> "${ERROR_FILE}"
+			cd ${BASEDIR}
 			return
 		fi
 		set -e
@@ -451,19 +457,6 @@ function debian_build {
 	cd ${BASEDIR}
 }
 
-function error_logging() {
-	if [ "${#ERROR_LOG[@]}" -gt 0 ]; then
-		echo "Failures:"
-		for item in "${ERROR_LOG[@]}"; do
-			echo "${item}"
-		done
-		exit 1
-	else
-		echo "Success."
-		exit 0
-	fi
-}
-
 if [ -z "$KERNEL_TYPE" ]; then
 	#
 	# Ubuntu build
@@ -597,7 +590,16 @@ if [ -z "$KERNEL_TYPE" ]; then
 	# Upload modules
 	#
 	aws s3 sync ./output/ s3://download.draios.com/$REPOSITORY_NAME/sysdig-probe-binaries/ --acl public-read
-	error_logging
+
+	if [ ! -s "${ERROR_FILE}" ]; then
+		rm ${ERROR_FILE}
+		echo "Success."
+		exit 0
+	else
+		echo "Failures:"
+		cat ${ERROR_FILE}
+		rm ${ERROR_FILE}
+		exit 1
 
 elif [ "OL6-UEK" = "$KERNEL_TYPE" ]; then
 	# This should only run in the ol6-builder container context
@@ -609,7 +611,6 @@ elif [ "OL6-UEK" = "$KERNEL_TYPE" ]; then
 	do
 		rhel_build $URL
 	done
-	error_logging
 elif [ "OL7-UEK" = "$KERNEL_TYPE" ]; then
 	# This should only run in the ol7-builder container context
 	echo Building Oracle Linux 7 UEK
@@ -620,7 +621,6 @@ elif [ "OL7-UEK" = "$KERNEL_TYPE" ]; then
 	do
 		rhel_build $URL
 	done
-	error_logging
 else
 	exit 1
 fi
