Support EL7

diff --git a/scripts/install-sysdig.in b/scripts/install-sysdig.in
--- a/scripts/install-sysdig.in
+++ b/scripts/install-sysdig.in
@@ -26,7 +26,11 @@ function install_rpm {
 
 	if ! yum -q list dkms > /dev/null 2>&1; then
 		echo "* Installing EPEL repository (for DKMS)"
-		rpm --quiet -i http://mirror.us.leaseweb.net/epel/6/i386/epel-release-6-8.noarch.rpm
+		if [ $VERSION -eq 7 ]; then
+						rpm --quiet -i http://mirrors.kernel.org/fedora-epel/beta/7/x86_64/epel-release-7-0.1.noarch.rpm
+		else
+						rpm --quiet -i http://mirrors.kernel.org/fedora-epel/6/i386/epel-release-6-8.noarch.rpm
+		fi
 	fi
 
 	echo "* Installing Draios public key"
@@ -67,23 +71,23 @@ function install_deb {
 }
 
 function unsupported {
-    echo 'Unsupported operating system. Please consider writing to the mailing list at'
-    echo 'https://groups.google.com/forum/#!forum/sysdig or trying the manual'
-    echo 'installation.'
-    exit 1
+	echo 'Unsupported operating system. Please consider writing to the mailing list at'
+	echo 'https://groups.google.com/forum/#!forum/sysdig or trying the manual'
+	echo 'installation.'
+	exit 1
 }
 
 function kernel_warning {
-    echo "Unable to find kernel development files for the current kernel version" $(uname -r)
-    echo "This usually means that your system is not up-to-date or you installed a custom kernel version."
-    echo "The installation will continue but you'll need to install these yourself in order to use sysdig."
-    echo 'Please write to the mailing list at https://groups.google.com/forum/#!forum/sysdig'
-    echo "if you need further assistance."
+	echo "Unable to find kernel development files for the current kernel version" $(uname -r)
+	echo "This usually means that your system is not up-to-date or you installed a custom kernel version."
+	echo "The installation will continue but you'll need to install these yourself in order to use sysdig."
+	echo 'Please write to the mailing list at https://groups.google.com/forum/#!forum/sysdig'
+	echo "if you need further assistance."
 }
 
 if [ $(id -u) != 0 ]; then
-    echo "Installer must be run as root (or with sudo)."
-    exit 1
+	echo "Installer must be run as root (or with sudo)."
+	exit 1
 fi
 
 echo "* Detecting operating system"
@@ -106,19 +110,19 @@ if [ -f /etc/debian_version ]; then
 	if [ $DISTRO = "Ubuntu" ]; then
 		VERSION=$(echo $VERSION | cut -d'.' -f1)
 		if [ $VERSION -ge 10 ]; then
-		    install_deb
+			install_deb
 		else
 			unsupported
 		fi
 	elif [ $DISTRO = "LinuxMint" ]; then
 		if [ $VERSION -ge 9 ]; then
-		    install_deb
+			install_deb
 		else
 			unsupported
 		fi
 	elif [ $DISTRO = "Debian" ]; then
 		if [ $VERSION -ge 6 ]; then
-		    install_deb
+			install_deb
 		elif [[ $VERSION == *sid* ]]; then
 			install_deb
 		else
@@ -130,19 +134,19 @@ if [ -f /etc/debian_version ]; then
 
 elif [ -f /etc/system-release-cpe ]; then
 	DISTRO=$(cat /etc/system-release-cpe | cut -d':' -f3)
-	VERSION=$(cat /etc/system-release-cpe | cut -d':' -f5)
+	VERSION=$(cat /etc/system-release-cpe | cut -d':' -f5 | cut -d'.' -f1)
 
 	if [ $DISTRO = "oracle" ] || [ $DISTRO = "centos" ] || [ $DISTRO = "redhat" ]; then
-		if echo $VERSION | grep -q ^6; then
+		if [ $VERSION -ge 6 ]; then
 			install_rpm
 		else
 			unsupported
 		fi
 	elif [ $DISTRO = "amazon" ]; then
-	    install_rpm
+		install_rpm
 	elif [ $DISTRO = "fedoraproject" ]; then
 		if [ $VERSION -ge 13 ]; then
-		    install_rpm
+			install_rpm
 		else
 			unsupported
 		fi
