proxy support in install script

diff --git a/scripts/install-sysdig.in b/scripts/install-sysdig.in
--- a/scripts/install-sysdig.in
+++ b/scripts/install-sysdig.in
@@ -18,6 +18,15 @@
 #
 set -e
 
+function set_proxy {
+    echo "* Using proxy ${1}"
+    export {http,https}_proxy="${1}"
+}
+
+function unset_proxy {
+    unset {http,https}_proxy
+}
+
 function install_rpm {
 	if ! hash curl > /dev/null 2>&1; then
 		echo "* Installing curl"
@@ -87,9 +96,56 @@ function kernel_warning {
 	echo "if you need further assistance."
 }
 
+function help {
+    echo "Usage: $(basename ${0}) [-p | --proxy] [-h | --help]"
+	echo "  proxy: if you are installing sysdig behind a proxy" 
+	echo "         (e.g. http://<proxy_endpoint>:<proxy_port> or http://<user>:<password>@<proxy_endpoint>:<proxy_port>)"
+	echo "  help: print this usage and exit"
+	echo
+	exit 1
+}
+
+function is_valid_value {
+	if [[ ${1} == -* ]] || [[ ${1} == --* ]] || [[ -z ${1} ]]; then
+		return 1
+	else
+		return 0
+	fi
+}
+
+while [[ ${#} > 0 ]]
+	do
+        key="${1}"
+
+        case ${key} in
+            -p|--proxy)
+                if is_valid_value "${2}"; then
+                    PROXY="${2}"
+                else
+                    echo "ERROR: no value provided for proxy endpoint option, use -h | --help for $(basename ${0}) Usage"
+                    exit 1
+                fi
+                shift
+                ;;
+            -h|--help)
+                help
+                exit 1
+                ;;
+            *)
+                echo "ERROR: Invalid option: ${1}, use -h | --help for $(basename ${0}) Usage"
+                exit 1
+                ;;
+        esac
+        shift
+    done
+
 if [ $(id -u) != 0 ]; then
 	echo "Installer must be run as root (or with sudo)."
 	exit 1
+fi
+
+if [ ! -z "${PROXY}" ]; then
+    set_proxy "${PROXY}"
 fi
 
 echo "* Detecting operating system"
@@ -178,3 +234,9 @@ elif [ -f /etc/system-release-cpe ]; then
 else
 	unsupported
 fi
+
+if [ ! -z "${PROXY}" ]; then
+    unset_proxy
+fi
+
+exit 0
